export const ROUTES = {
  HOME: "/",
  HOME_API: "/home",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  VERIFY_EMAIL: "/verify-email",
  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  PROFILE: (id: string) => `/profile/${id}`,
  CONTACT: "/contact",
  ADMIN_PANEL: "/admin",
  COUNTRIES: "/countries",
  COUNTRIES_API: "/countries",
  COUNTRY: (slug: string) => `/countries/${slug}`,
} as const;
