export const ROUTES = {
  HOME: "/",
  HOME_API: "/home",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  VERIFY_EMAIL: "/verify-email",
  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  PROFILE: (id: string) => `/profile/${id}`,
  CONTACT: "/contact",
  COUNTRIES: "/countries",
  COUNTRIES_API: "/countries",
  COUNTRY: (slug: string) => `/countries/${slug}`,
  COUNTRY_API: (slug: string) => `/countries/${slug}`,
  REGION: (countrySlug: string, RegionSlug: string) =>
    `/countries/${countrySlug}/${RegionSlug}`,

  REGIONS: "/regions",
  REGIONS_API: "/regions",
  ADMIN_PANEL: "/admin",
  ADMIN_PANEL_REGIONS: "/admin/regions",
  ADMIN_PANEL_REGIONS_ADD: "/admin/regions/add",
  ADMIN_PANEL_COUNTRIES: "/admin/countries",
  ADMIN_PANEL_COUNTRIES_ADD: "/admin/countries/add",
  ADMIN_PANEL_COUNTRIES_EDIT: (slug: string) => `/admin/countries/edit/${slug}`,
  ADMIN_PANEL_CATEGORIES_ADD: "/admin/categories/add",
  ADMIN_PANEL_PACKING_WAYS_ADD: "/admin/packing-ways/add",
  ADMIN_PANEL_CATEGORIES_REORDER: "/admin/categories/reorder",
  ADMIN_PANEL_History: "/admin/history",
  ADMIN_PANEL_Users: "/admin/users",
} as const;
